pipeline {

    agent {label "ec2"}

    stages{
        stage("Build") {
            steps{
                sh "docker build -t tal:$BUILD_NUMBER app/"
                }
            }
      
        stage("Push") {
            steps {
                sh """
                  aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 434339890453.dkr.ecr.eu-central-1.amazonaws.com
                  docker tag tal:$BUILD_NUMBER 434339890453.dkr.ecr.eu-central-1.amazonaws.com/myproject:$BUILD_NUMBER
                  docker push 434339890453.dkr.ecr.eu-central-1.amazonaws.com/myproject:$BUILD_NUMBER
                   """
            }
        }

    }
}
